### ISSUE TITLE
Order of deployment & logdy.json

### ISSUE THREAD

**Issue by frankievalentine** [FoxxMD/traefik-homelab#3]
Hey FoxxMD,

Thanks for this repo and write up on how you setup your homelab proxy and security. It is very extensive and detailed. I am deploying Traefik/Crowdsec in its own LXC container in Proxmox separately from a Komodo LXC container housing most of my homelab services. I won't be using Authentik in this setup and was going to use [TinyAuth](https://tinyauth.app/docs/getting-started.html) instead.

Regarding deployment order overall for this setup, from what I understand after setting up .env variable's and after editing CHANGEME's:

1. Create the traefik log directory `mkdir -p /var/log/traefik` on the server
2. Deploy crowdsec compose without crowdsec ingest
3. Exec into the crowdsec container and add machine `cscli machines add MyChildMachine --auto`
4. Redeploy with crowdsec-ingest included
5. Stop crowdsec and edit the config files to include username and password
6. Redeploy crowdsec compose.yaml
7. Deploy traefik-internal compose.yaml
8. Deploy traefik-external compose.yaml
9. Deploy traefik-kop compose.yaml

Also, as far as editing the lodgy.json file `handlerTsCode` CHANGEME's and IP's. I do not currently use IPV6 in my setup so I'm assuming I can just remove that code from there. Other than that I'm not really sure what to include there otherwise for the other CHANGEME's. If you have any more guidance as to how to navigate that it would be much appreciated.

If I have any of this incorrect please let me know and thanks for your time.

**Comment by FoxxMD** [comment]
I think your order looks fine. It's all pretty error-tolerant by just restarting anything after making changes so the order isn't too important other than obviously dependent steps (generate machine for crowdsec for example).

Yeah you can remove IPv6 condition without any issue.

For the changeme's in logdy:

* `external` is supposed to filter to IP addresses that are *not* in your local network *or* your own public IP
  * only relevant for `traefik_external`
  * If not using cloudflare tunnels and have local dns then filter out local address ranges as well
    * Should be *start* of IP range, not specific to one, so that all IPs in 192.168.0.X get detected
  * Could expand this to include VPN subnets too
*  `me` is supposed to be for IP addresses that are *not* the machines you usually browse your services on
   * only relevant for `traefik_internal`
   * Should be a set of specific IPs
   * Useful for filtering out your traffic so you can see how other devices/users on your network use your services

**Comment by frankievalentine** [comment]
Ok, great thanks for the feedback with the steps! I am not too familiar with Swarm yet so I am having some trouble with the networking aspect. For instance I followed these steps for creating Crowdsec:

1. Used `docker compose up -d` for the first instance of crowdsec without the `crowdsec_net` overlay network included because compose wouldn't recognize the overlay network.
2. Exec'd into the container and created the API Bouncer key
3. Created the crowdsec-ingest instance and initialized the config files
4. Downed the compose
5. Edited the `config.yaml` (the api was already disabled on this file... it seems to be enabled on the crowdsec instance and disabled on the ingest instance), `local_api_credentials.yaml`, and `acquis.yaml` files according to the article instructions
6. Then edited the compose.yaml to include the overlay network on both instances
7. Deployed the Swarm stack using `docker stack deploy -c compose.yaml crowdsec`

Please let me know if I am on the right track there or if I did more than I needed to.

Lastly, regarding your explanation regarding `lodgy.json` I guess I am getting confused because in the repo it shows that under the traefik-external directory it references "me" and in the traefik-internal directory it references "external" so it seems to be swapped? I am not sure if that is correct or not.

**Comment by frankievalentine** [comment]
Please disregard previous question. Thanks!

**Comment by frankievalentine** [comment]
I need to reopen this as I have more questions.

Does this configuration rely on having two separate public domains to replace i.e (.casa/.com)? Or are you supposed to create your own local certificates for the .casa LAN domain? Because traefik will only create SSL certs if you have a local certificate on a LAN only domain or a public domain for the `internalresolver`. If you need two public domains, how is DNS configured in Cloudflare aside from setting the tunnel configuration? Currently, I have only setup one public domain, and have all the internal services point to a subdomain on that public domain i.e. (local.homelab.com).

Deploying traefik-kop on another system gives me an error on the service stating that `traefik-kop-1  | level=info msg="skipping router <deployed service>@docker (not in namespace )"`. I am trying to route this service from my Komodo machine to the external traefik instance via the public_web overlay network. I have added the correct labels to this service (including `kop.namespace`) as described in the external example service and I have already joined the Komodo machine to the swarm.

When deploying the external service, do we have to reference the `cf` entrypoint?

It seems like I am mainly only having issues with the external configuration thus far. The internal configuration and crowdsec seem to be working just fine.

Here is a link to a repo (if helpful): https://github.com/frankievalentine/traefik-setup

**Comment by FoxxMD** [comment]
> Does this configuration rely on having two separate public domains to replace?

Yes. I am using two public domains registered with cloudflare.

> how is DNS configured in Cloudflare

One TLD is for internal services and one is for external. There is no overlap between the two. I use one subdomain per service.

For both domains the respective traefik instance uses [DNS challenege](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/) to provision one [wildcard cert for the entire domain using cloudflare api token.](https://blog.foxxmd.dev/posts/migrating-to-traefik/#wildcards)

For the internal subdomain no additional DNS records in cloudflare are required.

For the external subdomain all DNS records should be configured automatically if you setup the cloudflare tunnel in the CF dashboard. The CF tunnel config creates a cname with a unique name for the initial setup and then a cname for `*` when that public hostname is added to the tunnel (`*.yourdomain.com`) 

>  I have only setup one public domain, and have all the internal services point to a subdomain on that public domain

I don't think it's impossible to do routing this way but it certainly makes your setup more complicated. Both traefik instances need to provision for the same domain which may limit the type of cert you can get (not using wildcard?). You can't use wildcard routing for CF tunnel and it implies more config required in local dns (to use wildcard). It also makes separation of concerns more murky with a higher chance of accidentally routing an internal service to external, or vice versa, since they share a TLD.

> When deploying the external service, do we have to reference the cf entrypoint?

Since you have [`asDefault: true`](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/traefik/static-config/traefik.yaml#L38) for the cf entrypoint you should not need to do this.

> `skipping router <deployed service>@docker (not in namespace )`

Can you provide an example of the compose service w/ labels that this is occurring on?

**Comment by frankievalentine** [comment]
That makes much more sense that it's two public facing domains. It doesn't really work with one as you described. Should both of these domains be listed under the `internalresolver` or just the local TLD?

I do have the tunnel pointing to the _external traefik instance_. Do I have to point this to the internal traefik instance instead?

Here's an example service I have on the other machine.

```yaml
services:
  service:
    image: image
    container_name: service
    environment:
      - APP_URL=https://service.public.domain
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/service/storage:/app/data/storage
    networks:
     - database
     - store
     - public_web
    labels:
      traefik.enable: true
      traefik.docker.network: public_web
      traefik.http.routers.docmost.rule: Host(`service.public.domain`)
      traefik.http.services.docmost.loadbalancer.server.port: 3000
      kop.namespace: public

networks:
 public_web:
   external: true
 database:
    external: true
 store:
    external: true
```

Heres the traefik-kop compose from the other machine as well.

```yaml
services:
  traefik-kop:
    image: "ghcr.io/jittering/traefik-kop:latest"
    networks:
      - default
      - kop_net
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=traefik-external-redis:6379"
      - "DOCKER_HOST=tcp://socket-proxy:2375"
      - "BIND_IP=${BIND_IP}"
      - "KOP_HOSTNAME=${HOSTNAME:-generic}"
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    environment:
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      - CONTAINERS=1
      - INFO=1
      - NETWORKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    read_only: true
    tmpfs:
      - /run
networks:
  kop_net:
    external: true
```

I have the HOSTNAME env variable configured to be "public" and the BIND_IP variable configured to be the IP of the Traefik machine.

**Comment by FoxxMD** [comment]
> tunnel pointing to the external traefik instance.

This is correct. The tunnel is for forwarding public traffic to the public traefik instance (or entrypoint).

If you need a way to route `subdomainA.myinternaldomain.com` on your local network directly to traefik (lan-only traffic) then you need to setup [LAN-only dns.](https://blog.foxxmd.dev/posts/redundant-lan-dns/)

 > Should both of these domains be listed under the internalresolver or just the local TLD?

Just the local. If all external traffic goes through the one external domain using CF tunnels you never need to touch certs for it.

When you use Cloudflare tunnel for a domain **Cloudflare is the entity provisioning a tls certificate for you.** All the traffic for that domain (or subdomains, if configured that way) terminates at CF's server. Then, they forwarded encrypted traffic to your `cloudflared` instances which then forwards it to traefik, unencrypted. Traefik never deals with the certs.

Expand the **Why?** section under the [Cloudflare Tunnels](https://blog.foxxmd.dev/posts/migrating-to-traefik/#certs-and-cf-tunnels) heading for a more thorough explanation of this.

> Heres the traefik-kop compose 

Your `traefik-kop` `environment:` is missing the [`NAMESPACE`](https://github.com/jittering/traefik-kop?tab=readme-ov-file#namespaces) env. It should have `NAMESPACE=public`.

**Comment by frankievalentine** [comment]
LAN only DNS is setup on my network via Adguard Home using DNS rewrites (domain.public, and wildcard local DNS *.domain.public).

Since were using two public domains, the only other place I see referencing the external public domain listed in your config is under the traefik-external dynamic config here:

```yaml
http:
  middlewares:
    anyreg:
      redirectregex:
        regex: ^.*
        replacement: https://MY_SITE_CHANGEME.com
```

So this is the only configuration for traefik that tells CF to provision a TLS cert for the external domain. Is this correct?

Just a heads up, I did take the traefik-kop compose setup for the other host from your [guide](https://blog.foxxmd.dev/posts/migrating-to-traefik/#docker-standalone) and it doesn't include NAMESPACE in the env only the KOP_HOSTNAME.

I do see that traefik is receiving the external service configuration in the logs after adding the NAMESPACE env, but traefik-kop is giving an error `level=warning msg="router service@docker has no TLS cert resolver"` do I still have to provide the default labels such as `tls=true, entrypoints=cf` on the external service?

**Comment by frankievalentine** [comment]
When deploying the external service, do we have to reference the cf entrypoint?

> Since you have [`asDefault: true`](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/traefik/static-config/traefik.yaml#L38) for the cf entrypoint you should not need to do this.

I'm finding it strange that traefik is not using this as the default config. I am having to reference the entrypoint in the labels for it to work properly on both the internal and external traefik instances.

Also, since you have two redis services with exposed ports, are you changing the redis port on one traefik instance to be able to deploy both? I.e. `6380:6379`? Or removing the ports exposure on one instance altogether?

**Comment by FoxxMD** [comment]
> it doesn't include NAMESPACE in the env only the KOP_HOSTNAME.

The section you linked to is for the simple traefik-kop example where its being used to map all services from a remote host. That section is specifically for "how to get services into traefik from another machine"

In the following section on [Separating Internal/External Services](https://blog.foxxmd.dev/posts/migrating-to-traefik/#separating-internalexternal-services)  in the [By Isolated Network](https://blog.foxxmd.dev/posts/migrating-to-traefik/#by-isolated-docker-network) subsection I introduce namespaces and [provide examples that diff the previous examples to include namespaces.](https://blog.foxxmd.dev/posts/migrating-to-traefik/#separate-network-setup)

>  but traefik-kop is giving an error level=warning msg="router service@docker has no TLS cert resolver" 

This is a normal and can be ignored. It's still pushing the service configs to the trefik redis provider.

> since you have two redis services with exposed ports

This would be an oversight on my part. My instances are running on different machines so there's no issue with port conflicts. But since both instances are part of the overlay [`kop_net`](https://github.com/FoxxMD/traefik-homelab/blob/main/traefik_internal/compose.yaml#L71) network there is no need to expose ports on the host at all. The `ports` section for both can be removed. In the kop configuration (assuming you are using `kop_net`) they can be connected to using `service_name:internal_port` IE `traefik-internal-redis:6379` etc..

> So this is the only configuration for traefik that tells CF to provision a TLS cert for the external domain.

Which configuration? External? There is no TLS cert provisioning occurring on the traefik instance that uses cloudflare tunnels. Cert provisioning only occurs if [`certificateResolvers`](https://doc.traefik.io/traefik/https/acme/#configuration-examples) is present in the static config. Neither my [example external traefik](https://github.com/FoxxMD/traefik-homelab/blob/main/traefik_external/traefik/static_config/traefik.yaml) nor [your example](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/traefik/static-config/traefik.yaml) includes this.

> referencing entrypoints

If your traefik entrypoints are still setup the way they are in your [example repo](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-internal/traefik/static-config/traefik.yaml) you should not need to reference entrypoints at all. Take a look at the [`asDefault`](https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/#asdefault) documentation.

**Comment by frankievalentine** [comment]
> The section you linked to is for the simple traefik-kop example where its being used to map all services from a remote host. That section is specifically for "how to get services into traefik from another machine"

Correct, that is exactly what I am referencing. I am using that simple traefik-kop example to map all services from my remote host. Which you previously mentioned needs to specifically have the NAMESPACE env variable listed. I was just letting you know that the simple example you provided is missing the NAMESPACE env to map all services from the remote host.

> Which configuration? External? There is no TLS cert provisioning occurring on the traefik instance that uses cloudflare tunnels. Cert provisioning only occurs if [`certificateResolvers`](https://doc.traefik.io/traefik/https/acme/#configuration-examples) is present in the static config. Neither my [example external traefik](https://github.com/FoxxMD/traefik-homelab/blob/main/traefik_external/traefik/static_config/traefik.yaml?rgh-link-date=2025-07-24T18%3A21%3A41.000Z) nor [your example](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/traefik/static-config/traefik.yaml?rgh-link-date=2025-07-24T18%3A21%3A41.000Z) includes this.

In the repo, this is the only part of the external configuration that references the external public domain:
```yaml
http:
  middlewares:
    anyreg:
      redirectregex:
        regex: ^.*
        replacement: https://MY_SITE_CHANGEME.com
```
I guess my question was attempting to figure out what this middleware accomplishes?

> If your traefik entrypoints are still setup the way they are in your [example repo](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-internal/traefik/static-config/traefik.yaml?rgh-link-date=2025-07-24T18%3A21%3A41.000Z) you should not need to reference entrypoints at all. Take a look at the [`asDefault`](https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/#asdefault) documentation.

Yes, they are correctly configured asDefault, but not utilizing those entrypoints unless I specify them in the labels. So I'm wondering if you have any insight as to why that would be.

Again, thanks for your help, I really appreciate your time as this is driving me a bit mad.

**Comment by FoxxMD** [comment]
> you previously mentioned needs to specifically have the NAMESPACE env variable listed. 

This is based on the [example from your comment](https://github.com/FoxxMD/traefik-homelab/issues/3#issuecomment-3090150284) in reference to the log you were seeing `skipping router <deployed service>@docker (not in namespace )`...

If no `NAMESPACE` is defined on traefik-kop then it'll publish the router for any service that **does not** have a `kop.namepsace` label. If `NAMESPACE` is defined then it'll only publish services that also have a label for `kop.namespace=NAMESPACE`.

[Your example](https://github.com/FoxxMD/traefik-homelab/issues/3#issuecomment-3090150284) has a service with `kop.namespace=public` label but the traefik-kop example did not have `NAMESPACE` env.

> the simple example you provided is missing the NAMESPACE env to map all services from the remote host.

The simple example, unrelated to your example, does not introduce namespace env or labels. If someone was to use that as-is -- as in just the example and _not_ including namespace label that hasn't been introduced yet -- it would work without issue. Namespace env and labels are only introduced in-tandem, later on.

I'm not sure why you think the example that intentionally doesn't include the namespace concept would work with the `kop.namespace` label/concept. The namespace section is pretty clear they are used together, as is the traefik-kop docs.

> what this middleware accomplishes?

This is the [redirect on non-existent route middleware](https://blog.foxxmd.dev/posts/migrating-to-traefik/#redirect-on-non-existent-route) from the How-To's section.

> not utilizing those entrypoints unless I specify them in the labels.

What happens when they aren't specified? Have you turned on a more verbose [logging level](https://doc.traefik.io/traefik/observability/logs/#level) for traefik to see if it gives you any hints when starting up? Can you see any of the routes/services in the [dashboard](https://doc.traefik.io/traefik/operations/dashboard/) and if so what discrepancies can you see? Are they missing? Assigned to a different entrypoint?

**Comment by frankievalentine** [comment]
> This is based on the [example from your comment](https://github.com/FoxxMD/traefik-homelab/issues/3#issuecomment-3090150284) in reference to the log you were seeing `skipping router <deployed service>@docker (not in namespace )`...
> 
> If no `NAMESPACE` is defined on traefik-kop then it'll publish the router for any service that **does not** have a `kop.namepsace` label. If `NAMESPACE` is defined then it'll only publish services that also have a label for `kop.namespace=NAMESPACE`.
> 
> [Your example](https://github.com/FoxxMD/traefik-homelab/issues/3#issuecomment-3090150284) has a service with `kop.namespace=public` label but the traefik-kop example did not have `NAMESPACE` env.
> 
> > the simple example you provided is missing the NAMESPACE env to map all services from the remote host.
> 
> The simple example, unrelated to your example, does not introduce namespace env or labels. If someone was to use that as-is -- as in just the example and _not_ including namespace label that hasn't been introduced yet -- it would work without issue. Namespace env and labels are only introduced in-tandem, later on.
> 
> I'm not sure why you think the example that intentionally doesn't include the namespace concept would work with the `kop.namespace` label/concept. The namespace section is pretty clear they are used together, as is the traefik-kop docs.

I see what you are saying. Apologies. Thank you.

My issues must be stemming from both Traefik instances being on one VM.

**Comment by FoxxMD** [comment]
Other than the redis ports I'm not sure why having both instances on the same machine would cause these issues.

Did investigating logs/dashboard turn up anything? Is your [setup repo](https://github.com/frankievalentine/traefik-setup) still up to date?

**Comment by frankievalentine** [comment]
Yes you are correct, both instances on the same machine is fine. This is now in a more working state internally. I went ahead and added `traefik.docker.network: internal_web` and `kop.namespace: internal` labels to the internal/external services i.e. traefik, logdy, and the whoami test in my traefik-internal compose. 

Everything seems to be working correctly there after adding those labels, but only the traefik-external dashboard seems to give me a `504 Gateway Timeout error="dial tcp 10.99.0.22:8080: i/o timeout"` error after some time and no longer continues to work with those same labels I added on the traefik-internal compose.

Also, the Cloudflare Tunnel service I am attempting to deploy on the other machine seems to now be in the correct configuration except I am getting a `502 Bad Gateway error="dial tcp 10.99.0.20:8080: connect: connection refused"` in the traefik logs. I am wondering if this is due to an incorrect DNS configuration via Cloudflare, or if I need to add my public IP (from my ISP) to the `trustip` range in my traefik-external dynamic config under the cloudflare-warp plugin.

And yes, the [setup repo](https://github.com/frankievalentine/traefik-setup?rgh-link-date=2025-07-28T14%3A39%3A16.000Z) is up to date with my current config.

**Comment by FoxxMD** [comment]
> `502 Bad Gateway error` for cloudflare/traefik external

What is at `10.99.0.20`? Is this what traefik logs when trying to access a proxied service? What do you have set for **Service** in your CF Tunnel for the external public hostname? It should look like this

<img width="649" height="500" alt="Image" src="https://github.com/user-attachments/assets/4d0bc203-a6de-4dae-952d-8fb35d29d6ea" />

**Comment by frankievalentine** [comment]
`10.99.0.20` is the ip for that service under the public_web endpoint. That's what the traefik logs are providing when trying to access the proxied service. Currently, I have the container name `traefik-external` setup under **Service** in my CF Tunnel config. It was my understanding that container names go there for CF Tunnels. Is that correct to use the container name for Traefik there?

**Comment by FoxxMD** [comment]
Yes that should be fine.

Can you provide an example of the service at `10.99.0.20`, in your traefik-setup repo?

It sounds like there is an issue with the overlay network or how the service (or traefik) is connected to it.

1. **Verify proxied service is attached to network and IP**

On the host running the proxied service find the container's name with `docker container ls` and then do

```
docker container inspect CONTAINER_NAME_OR_ID
```

At the bottom of the output ensure it has a `public_endpoint` object in the `Networks` section. It should look something like this

```
                "public_web": {
                    "IPAMConfig": {
                        "IPv4Address": "10.99.0.20"
                    },
                    "Links": null,
                    "Aliases": [
                        "myService",
                        "myService"
                    ],
                    "MacAddress": "02:42:0a:00:06:04",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "xndsfkhgludbpj7u28d6tmdse",
                    "EndpointID": "e2b841e4bfc2520f31bcb081d7c267c0b8b6d9ede8f988a130f6520395c5c358",
                    "Gateway": "",
                    "IPAddress": "10.99.0.20",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "myService",
                        "4111d89248d1"
                    ]
                },

```

* If you don't see the network attached then check your `networks` fields at [top-level](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/compose.yaml#L138) and the [service-level](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/compose.yaml#L5) in the compose stack 
* If there is one attached but its named like `myService-public_web` then the network was created by the stack rather than being attached to the external network
* If the above are correct but the IP is wrong then traefik-kop is mapping the wrong network, for some reason
  * Make sure that `traefik.docker.network` label is defined and set to `public_web`

2. **Verify traefik is attached to network and IP**

Do the above again but for the traefik container, except for traefik-kop. Just need to verify that traefik is in the network as expected.

3. **Check connectivity between traefik and the proxied service**

Shell into the traefik container and check if you can reach the host

```sh
docker container exec -it TRAEFIK_CONTAINER_NAME_OR_ID /bin/sh
apk add nmap
nmap -sn 10.99.0.20
```

If the IP is reachable nmap will return with `Nmap done: 1 IP address (1 host up) scanned in 0.22 seconds`.

If nmap can't reach it there is an issue with inter-container networking on the network. If both containers are on the same host then ???? idk. If you are using an overlay and containers are on different hosts then make sure [port `4789` for UDP is open on all hosts in the swarm.](https://docs.docker.com/engine/swarm/networking/#firewall-considerations)

In either case you should also check docker logs, usually `journalctl -u docker`, to see if there are any issues occurring.

3. **Check container app specifics**

If the host is reachable from the above step using `nmap` then you need to verify if the app running in the proxied service container is configured for communication correctly.

From the traefik container in step 2 scan for the port that the proxied serivce should be open on

```sh
nmap -p 8080 10.99.0.20
```
If the namp results show `STATE` as anything other than `open`  (`closed` or `filtered`) then the app is not accepting traffic on the port you mapped it to. Something things you can do to diagnose this:

* `exec` into the proxied service container and try `curl` or `nmap` the port from there, if open then maybe the service is listening on the wrong interface/address
* double check the traefik `server.port` label on the proxied service -- this should be the **internal** port, not a **published** port IE if the service would normally have something like this in the compose.yaml stack

```yaml
services:
  myService:
   #...
   ports:
     - "8080:5003"
```

Then the traefik label should be like

```
traefik.http.services.myService.loadbalancer.server.port: 5003
```

**Comment by frankievalentine** [comment]
> double check the traefik `server.port` label on the proxied service -- this should be the **internal** port, not a **published** port IE if the service would normally have something like this in the compose.yaml stack
> 
> 
> services:
>   myService:
>    #...
>    ports:
>      - "8080:5003"
> 
> Then the traefik label should be like
> 
> ```
> traefik.http.services.myService.loadbalancer.server.port: 5003
> ```

This was the problem I had the loadbalancer port as 8080 on the service. Thanks for your help with that and the extended debug explanation.


> Yes you are correct, both instances on the same machine is fine. This is now in a more working state internally. I went ahead and added `traefik.docker.network: internal_web` and `kop.namespace: internal` labels to the internal/external services i.e. traefik, logdy, and the whoami test in my traefik-internal compose.
>
> Everything seems to be working correctly there after adding those labels, but only the traefik-external dashboard seems to give me a `504 Gateway Timeout error="dial tcp 10.99.0.22:8080: i/o timeout"` error after some time and no longer continues to work with those same labels I added on the traefik-internal compose.

Could you help me figure out why the `traefik-external` dashboard does not continue to resolve when using these labels? If I restart traefik it will resolve for a bit and then it will show that timeout error listed above.

```yaml
traefik:
    image: traefik:v3.5
    container_name: traefik-external
    networks:
      - public_web
      - traefik_internal
      - crowdsec_net
    depends_on:
      - traefik-external-redis
    ports:
      # - "80:80"
      # - "443:443"
      - "8080:8080"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CS_TRAEFIK_BOUNCER_KEY: ${CS_TRAEFIK_BOUNCER_KEY}
      BOUNCER_HOST: ${BOUNCER_HOST}
    volumes:
      - ./traefik/letsencrypt:/letsencrypt
      - ./traefik/certificates:/certificates
      - ./traefik/log:/var/log/traefik:rw
      - ./traefik/static-config/traefik.yml:/etc/traefik/traefik.yml:rw
      - ./traefik/dynamic-config:/config/dynamic:rw
      - ./traefik/ban.html:/config/ban.html:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-dashboard-external.rule: Host(`traefik-external.<domain>`)
      traefik.http.services.traefik-dashboard-external.loadbalancer.server.port: 8080
      traefik.docker.network: public_web
      kop.namespace: public
      kop.traefik-dashboard-external.bind.ip: "10.0.0.<ip>"
```

**Comment by FoxxMD** [comment]
Make sure that traefik static config has the [dashboard enabled](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-external/traefik/static-config/traefik.yaml#L15)

```yaml
api:
  dashboard: true
  insecure: true
```

But the issue is more likely your traefik labels.

```
      traefik.enable: true
      traefik.http.routers.traefik-dashboard-external.rule: Host(`traefik-external.<domain>`)
      traefik.http.services.traefik-dashboard-external.loadbalancer.server.port: 8080
      traefik.docker.network: public_web
      kop.namespace: public
```

Keep in mind that the [dashboard](https://doc.traefik.io/traefik/operations/dashboard/) should **only be accessible within your home network**. You do not want it to be served to the public internet. It contains all of your routes, internal ips for service, and a decent amount of middleware config. It's not for public use.

Right now your labels are setup to try to serve it publicly since you have told kop to map it for traefik external (`kop.namespace: public`) and use the address for the public_web network (`traefik.docker.network: public_web`) to proxy it.

The end result you actually want is that the dashboard is proxied to the **internal** traefik instance.

Since traefik external has no overlap with the `internal_web` network (intentionally), we instead need to tell traefik internal to proxy to it using **regular host bridge networking.** 

Instead of what we are doing with all other services -- proxying through private docker IPs on the share `internal_web` or `public_web` networks -- we are proxying directly through a machine's `host:port`. So the traefik dashboard will be accessible directly at `192.168.your.ip:8080` and, critically, not accessible through external traefik proxying. 

1. Publish port to bridge network

you've already done this with 

```yaml
    ports:
      - "8080:8080"
```

2. Define traefik and service to use for internal traefik

Make sure that ``Host(`traefik-external.<domain>`)`` is pointing to subdomain/host that is **only accessible from traefik internal**.

```
traefik.http.services.traefik-dashboard-external.loadbalancer.server.port: 8080
```

This is already correct but FYI when proxying traffic via bridge network (instead of `internal_web`) we need the port to be the **published** port, rather than the internal port like in my last post.

3. Define traefik-kop mappings for traefik internal when using bridge networking

Since we aren't routing through a docker network remove `traefik.docker.network: public_web`.

Change namespace to `internal`

Depending on how [kop is setup with BIND_IP](https://github.com/frankievalentine/traefik-setup/blob/main/traefik-kop/compose.yaml#L18) it may not be necessary to use the `bind.ip` label but I would try it with this defined first, then delete if it ends up working: set `bind.ip` label to the host IP.

Example of all the above as excerpts of your sample:

```yaml
traefik:
    image: traefik:v3.5
    # ...
    ports:
      - "8080:8080"
    # ...
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-dashboard-external.rule: Host(`traefik-external.<AN_INTERNAL_DOMAIN>`)
      traefik.http.services.traefik-dashboard-external.loadbalancer.server.port: 8080
      kop.namespace: internal
      kop.traefik-dashboard-external.bind.ip: "192.168.0.100"
```

See the [traefik external setup in this repo](https://github.com/FoxxMD/traefik-homelab/blob/main/traefik_external/compose.yaml#L27), which does the same thing.
